SOURCE_SCAN = "scan"
SOURCE_MANUAL = "manual"
SOURCE_IMPORT = "import"

PHONE_TYPE_PERSONAL = "personal"
PHONE_TYPE_LANDLINE = "landline"
PHONE_TYPE_COMPANY = "company"
PHONE_TYPE_OTHER = "other"

PHONE_TYPES = (
    PHONE_TYPE_PERSONAL,
    PHONE_TYPE_LANDLINE,
    PHONE_TYPE_COMPANY,
    PHONE_TYPE_OTHER,
)
